locations = ['Elmira', 'Corning', 'Big Flats', 'Rochester']
print(locations)
print(sorted(locations))
print(locations)
locations_reverse = locations.sort(reverse=True)
print(locations_reverse)
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)